"""Evaluate projected detector cache against full Wildtrack/MultiviewX annotations."""
import argparse
import json
import os

import numpy as np
from scipy.optimize import linear_sum_assignment

from multiview_detector.datasets.MultiviewX import MultiviewX
from multiview_detector.datasets.Wildtrack import Wildtrack
from multiview_detector.utils.projection import get_worldcoord_from_imagecoord


def match_frame(detections, ground_truth, max_distance_m):
    if len(detections) == 0 or len(ground_truth) == 0:
        return []
    distances = np.linalg.norm(detections[:, None, :2] - ground_truth[None, :, :], axis=2)
    costs = np.where(distances <= max_distance_m, distances, max_distance_m + 1000.0)
    det_indices, gt_indices = linear_sum_assignment(costs)
    return [(int(di), int(gi), float(distances[di, gi]))
            for di, gi in zip(det_indices, gt_indices)
            if distances[di, gi] <= max_distance_m]


def summarize(matches, detection_count, ground_truth_count):
    true_positive = len(matches)
    precision = true_positive / detection_count if detection_count else 0.0
    recall = true_positive / ground_truth_count if ground_truth_count else 0.0
    errors = np.asarray([item[2] for item in matches], dtype=np.float64)
    median_error = float(np.median(errors)) if errors.size else float('nan')
    p90_error = float(np.percentile(errors, 90)) if errors.size else float('nan')
    return (f'dets={detection_count} gt={ground_truth_count} matched={true_positive} '
            f'precision={precision:.3f} recall={recall:.3f} '
            f'localization_median={median_error:.3f}m p90={p90_error:.3f}m')


def suppress_points(detections, radius_m):
    """Merge repeated cross-view projections with the detector's BEV NMS radius."""
    if len(detections) == 0:
        return np.empty((0, 3), dtype=np.float64)
    order = np.argsort(detections[:, 2])[::-1]
    kept = []
    for index in order:
        point = detections[index]
        if all(np.linalg.norm(point[:2] - detections[kept_index, :2]) > radius_m
               for kept_index in kept):
            kept.append(int(index))
    return detections[kept]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dataset', choices=['wildtrack', 'multiviewx'], required=True)
    parser.add_argument('--data_root', required=True, help='Dataset root with full annotations/calibration')
    parser.add_argument('--cache', required=True, help='Detection cache generated by generate_pseudo_cache.py')
    parser.add_argument('--confidence', type=float, default=0.2)
    parser.add_argument('--match_radius_m', type=float, nargs='+', default=[0.5, 1.0, 2.0])
    parser.add_argument('--fuse_radius_m', type=float, default=0.5,
                        help='Cross-view BEV NMS radius; 0.5 m matches MVDet test-time NMS')
    args = parser.parse_args()

    base_cls = Wildtrack if args.dataset == 'wildtrack' else MultiviewX
    base = base_cls(os.path.expanduser(args.data_root))
    world_to_meters = 0.01 if args.dataset == 'wildtrack' else 1.0
    with open(args.cache, 'r', encoding='utf-8') as cache_file:
        cache = json.load(cache_file)
    cache_dataset = cache.get('dataset')
    if cache_dataset and cache_dataset.lower() != args.dataset:
        raise ValueError(f'Cache is for {cache_dataset}, not {args.dataset}')
    frame_cache = cache.get('detections', {})
    annotation_dir = os.path.join(base.root, 'annotations_positions')

    detections_by_camera = [[] for _ in range(base.num_cam)]
    gt_by_camera = [[] for _ in range(base.num_cam)]
    detections_by_frame = {}
    gt_by_frame = []
    for filename in sorted(os.listdir(annotation_dir)):
        if not filename.endswith('.json'):
            continue
        frame = int(os.path.splitext(filename)[0])
        with open(os.path.join(annotation_dir, filename), 'r', encoding='utf-8') as annotation_file:
            people = json.load(annotation_file)
        frame_detections = frame_cache.get(str(frame), {})
        for camera in range(base.num_cam):
            camera_detections = frame_detections.get(str(camera), [])
            image_points, scores = [], []
            for detection in camera_detections:
                if isinstance(detection, dict):
                    box = detection.get('bbox', detection.get('box'))
                    score = float(detection.get('confidence', detection.get('score', 0.0)))
                else:
                    if len(detection) < 5:
                        continue
                    box, score = detection[:4], float(detection[4])
                if box is None or score < args.confidence:
                    continue
                x1, y1, x2, y2 = map(float, box)
                if not np.isfinite([x1, y1, x2, y2, score]).all() or x2 <= x1 or y2 <= y1:
                    continue
                image_points.append([(x1 + x2) * 0.5, y2])
                scores.append(score)
            if image_points:
                world_points_native = get_worldcoord_from_imagecoord(
                    np.asarray(image_points, dtype=np.float64).T,
                    base.intrinsic_matrices[camera], base.extrinsic_matrices[camera]).T
                grid_points = base.get_worldgrid_from_worldcoord(world_points_native.T).T
                if base.indexing == 'xy':
                    inside = ((grid_points[:, 0] >= 0) & (grid_points[:, 0] < base.worldgrid_shape[1]) &
                              (grid_points[:, 1] >= 0) & (grid_points[:, 1] < base.worldgrid_shape[0]))
                else:
                    inside = ((grid_points[:, 0] >= 0) & (grid_points[:, 0] < base.worldgrid_shape[0]) &
                              (grid_points[:, 1] >= 0) & (grid_points[:, 1] < base.worldgrid_shape[1]))
                world_points = world_points_native[inside] * world_to_meters
                scores = np.asarray(scores, dtype=np.float64)[inside]
                if len(scores):
                    dets = np.column_stack((world_points, scores))
                    detections_by_camera[camera].append((frame, dets))
                    detections_by_frame.setdefault(frame, []).extend(dets.tolist())
            visible_gt = []
            for person in people:
                box = person['views'][camera]
                if box['xmin'] < 0 or box['xmax'] < 0 or box['ymin'] < 0 or box['ymax'] < 0:
                    continue
                visible_gt.append(base.get_worldcoord_from_pos(person['positionID']).astype(np.float64) * world_to_meters)
            gt_by_camera[camera].append((frame, np.asarray(visible_gt, dtype=np.float64).reshape(-1, 2)))
        gt_by_frame.append((frame, np.asarray([
            base.get_worldcoord_from_pos(person['positionID']).astype(np.float64) * world_to_meters
            for person in people], dtype=np.float64).reshape(-1, 2)))

    for radius in args.match_radius_m:
        all_matches = []
        total_detections = total_ground_truth = 0
        print(f'\nMatch radius: {radius:.2f} m')
        for camera in range(base.num_cam):
            detection_frames = dict(detections_by_camera[camera])
            camera_matches = []
            camera_detections = camera_ground_truth = 0
            for frame, gt in gt_by_camera[camera]:
                dets = detection_frames.get(frame, np.empty((0, 3), dtype=np.float64))
                camera_detections += len(dets)
                camera_ground_truth += len(gt)
                camera_matches.extend(match_frame(dets, gt, radius))
            all_matches.extend(camera_matches)
            total_detections += camera_detections
            total_ground_truth += camera_ground_truth
            print(f'cam{camera}: {summarize(camera_matches, camera_detections, camera_ground_truth)}')
        print(f'all: {summarize(all_matches, total_detections, total_ground_truth)}')

        fused_matches = []
        fused_detection_count = fused_ground_truth_count = 0
        for frame, gt in gt_by_frame:
            frame_dets = np.asarray(detections_by_frame.get(frame, []), dtype=np.float64).reshape(-1, 3)
            frame_dets = suppress_points(frame_dets, args.fuse_radius_m)
            fused_detection_count += len(frame_dets)
            fused_ground_truth_count += len(gt)
            fused_matches.extend(match_frame(frame_dets, gt, radius))
        print(f'fused-bev (NMS {args.fuse_radius_m:.2f} m): '
              f'{summarize(fused_matches, fused_detection_count, fused_ground_truth_count)}')


if __name__ == '__main__':
    main()
